# Demonstration for locator

This Jupyter Notebook will demonstrate all the functions in the `locator` module with some examples. The `locator` module encompasses the fowllowing features:

- `great_circle_distance` function: It is used to calculate the great circle distance (in metres) between pairs of points specified as latitudes and longitudes on a spherical Earth.
- `GeospatialLocator` class: It is a class to refer to a postcode database file and a population grid file and search for the postcodes and population in a certain range. It contains the three primary functions:
    - `get_postcodes_by_radius`: This function returns postcodes within specific distances of input location.
    - `get_population_data`: This function read the .asc file and get population data of each 1km x 1km grid cell as well as the latitude and longitude associated with the centre of each grid cell.
    - `get_population_by_radius`: This function returns the population within specific distances of input location.

Firstly import all the packages needed.

In [6]:
import numpy as np
from deepimpact.locator import great_circle_distance
from deepimpact.locator import GeospatialLocator

## Demos for `get_postcodes_by_radius`

The function has two parameters:
- **latlon1** (an array-like input): latitudes and longitudes of the first point (with the dimension of [n, 2] for n points)
- **latlon2** (an array-like input): latitudes and longitudes of the second point (with the dimension of [m, 2] for m points or [2] for a single point)

It will return a **numpy.ndarray** with the dimension of n x m, which contains the distance in metres between each pair of points.


To calculate the distance between two points:

In [7]:
distance_result1 = great_circle_distance([[20, 0]], [30, 50])

print(distance_result1)

[[5119829.23871481]]


To calculate the distances between two points and a specific points respectively:

In [8]:
distance_result2 = great_circle_distance([[10, -60], [-100, 20]], [180, 0])

print(distance_result2)

[[13287649.65109739]
 [ 8963280.06215398]]


To calculate the distances between any two points given two lists of points:

In [9]:
distance_result3 = great_circle_distance([[25, 35], [-120, -60], [78, -32]],
                                         [[13, 90], [-98, -68], [-162, 55]])

print(distance_result3)

[[ 5895191.16429116 12560876.91913225 17807481.10842513]
 [ 8547946.28297326  2457780.19505185  9582603.52584544]
 [ 9288113.67903885 19210584.72263183 12033155.58773886]]


## Demos for `GeospatialLocator`

Firstly creat a `GeospatialLocator` class called loc.

In [10]:
loc = GeospatialLocator()

### 1. `get_postcodes_by_radius`

The function has two parameters:
- **X** (an array-like input): a latitude-longitude pair of the centre location
- **radii** (an array-like input): an array of radial distances from X

It will return a **list of lists** that contains the lists of postcodes closer than the elements of radii to the location X.

To find the postcodes within a specific distance of an input location.

In [13]:
postcode_result1 = loc.get_postcodes_by_radius((51.4981, -0.1773), [0.1e3])
postcode_result2 = loc.get_postcodes_by_radius((52.2074, 0.1170), [1e3])

print(postcode_result1)
print(postcode_result2)

[['SW7 2AZ']]
[['CB1 0SA', 'CB1 0SB', 'CB1 0SD', 'CB1 0SE', 'CB1 0SF', 'CB1 0SG', 'CB1 0SH', 'CB1 0SJ', 'CB1 0SL', 'CB1 0SP', 'CB1 0SQ', 'CB1 0SR', 'CB1 0SS', 'CB1 0ST', 'CB1 0SU', 'CB1 1AH', 'CB1 1AP', 'CB1 1AR', 'CB1 1AZ', 'CB1 1DP', 'CB1 1DU', 'CB1 1EE', 'CB1 1EG', 'CB1 1EH', 'CB1 1EJ', 'CB1 1EL', 'CB1 1EQ', 'CB1 1ER', 'CB1 1ES', 'CB1 1EW', 'CB1 1EX', 'CB1 1EY', 'CB1 1EZ', 'CB1 1HA', 'CB1 1HE', 'CB1 1JE', 'CB1 1JH', 'CB1 1JJ', 'CB1 1JL', 'CB1 1JN', 'CB1 1JP', 'CB1 1JR', 'CB1 1JS', 'CB1 1JT', 'CB1 1JU', 'CB1 1JW', 'CB1 1JX', 'CB1 1JY', 'CB1 1JZ', 'CB1 1LA', 'CB1 1LB', 'CB1 1LD', 'CB1 1LE', 'CB1 1LF', 'CB1 1LG', 'CB1 1LH', 'CB1 1LJ', 'CB1 1LL', 'CB1 1LN', 'CB1 1LQ', 'CB1 1LR', 'CB1 1LS', 'CB1 1NE', 'CB1 1NL', 'CB1 1NP', 'CB1 1PA', 'CB1 1PN', 'CB1 1PR', 'CB1 1PW', 'CB2 1AA', 'CB2 1AB', 'CB2 1AD', 'CB2 1AG', 'CB2 1AX', 'CB2 1BY', 'CB2 1DB', 'CB2 1DQ', 'CB2 1QA', 'CB2 1QG', 'CB2 1QH', 'CB2 1QJ', 'CB2 1QP', 'CB2 1QQ', 'CB2 1QR', 'CB2 1QU', 'CB2 1QW', 'CB2 1QX', 'CB2 1QY', 'CB2 1QZ', 'CB2 

To find the postcodes within multiple distances of an input location.

In [14]:
postcode_result3 = loc.get_postcodes_by_radius((51.4981, -0.1773), [1.5e3, 4.0e3])
postcode_result4 = loc.get_postcodes_by_radius((52.2074, 0.1170), [0.2e3, 0.1e3])

print(postcode_result3)
print(postcode_result4)

[['SW100AD', 'SW100AE', 'SW100AG', 'SW100AH', 'SW100AJ', 'SW100AL', 'SW100AN', 'SW100AP', 'SW100AQ', 'SW100AR', 'SW100AS', 'SW100AU', 'SW100AW', 'SW100AX', 'SW100BG', 'SW100BQ', 'SW109AJ', 'SW109AL', 'SW109AN', 'SW109AP', 'SW109BN', 'SW109BP', 'SW109BS', 'SW109BT', 'SW109BW', 'SW109DS', 'SW109DZ', 'SW109EA', 'SW109FW', 'SW109HD', 'SW109HE', 'SW109HF', 'SW109HH', 'SW109HL', 'SW109HP', 'SW109HQ', 'SW109HR', 'SW109HT', 'SW109HU', 'SW109HW', 'SW109HX', 'SW109HY', 'SW109HZ', 'SW109JA', 'SW109JB', 'SW109JE', 'SW109JG', 'SW109JH', 'SW109JJ', 'SW109JP', 'SW109JQ', 'SW109JR', 'SW109JT', 'SW109JU', 'SW109JX', 'SW109JY', 'SW109JZ', 'SW109LA', 'SW109LB', 'SW109LE', 'SW109LF', 'SW109LG', 'SW109LH', 'SW109LJ', 'SW109LL', 'SW109LN', 'SW109LP', 'SW109LQ', 'SW109LR', 'SW109LS', 'SW109LW', 'SW109NB', 'SW109NE', 'SW109NF', 'SW109NJ', 'SW109NL', 'SW109NN', 'SW109NP', 'SW109NQ', 'SW109NR', 'SW109NW', 'SW109NY', 'SW109NZ', 'SW109PA', 'SW109PB', 'SW109PD', 'SW109PE', 'SW109PF', 'SW109PJ', 'SW109PN', 'SW109PR

### 2. `get_population_by_radius`

The function has two parameters:
- **X** (an array-like input): a latitude-longitude pair of the centre location
- **radii** (an array-like input): an array of radial distances from X

It will return a **list of lists** that contains the population closer than the elements of radii to the location X. The output should be the same shape as the radii array.

To calculate the population within a specific distance of an input location.

In [18]:
population_result1 = loc.get_population_by_radius((52.2074, 0.1170), [2e4])

print(population_result1)

[344017]


For the condition that is within a specific distance of an input location without any people around (such as in the sea):

In [19]:
population_result2 = loc.get_population_by_radius_optimized((60.7584, 2.6892), [2e3])

print(population_result2)

[0]


To calculate the population within multiple distances of an input location.

In [20]:
population_result3 = loc.get_population_by_radius((51.4981, -0.1773), [1e2, 5e2, 1e3])

print(population_result3)

[0, 7412, 27794]


It can be found that if the searching range is very small, it is possible that the range of circle does not include any centres of the 1km x 1km grid cells, then the output is possible to be 0. Therefore, we optimized the `get_population_by_radius` function to find the nearest grid center if the searching range is too small. Then we multiply the population of the nearest grid center by the area ratio of the searching circle and the grid cell. By this optimization, the population will then never output 0. The following code demonstrates the optimized function called `get_population_by_radius_optimized`.

In [21]:
population_result4 = loc.get_population_by_radius_optimized((51.4981, -0.1773), [1e2, 5e2, 1e3])

print(population_result4)

[232, 7412, 27794]
